import Head from "next/head";
import MainLayout from "@/layouts/MainLayout";
import Post from "@/components/Post";

export default function Home() {
  return (
    <>
      <Head>
        <title>Разминка - блог</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainLayout>
        <div className="flex flex-col gap-5 my-8">
          <Post />
          <Post />
          <Post />
        </div>
      </MainLayout>
    </>
  );
}
